### ISSUE TITLE
Upgraded to Github Enterprise, now I see an error

### ISSUE THREAD

**Issue by helsont** [noqcks/pull-request-size#132]
<img width="1045" alt="image" src="https://github.com/noqcks/pull-request-size/assets/1709344/71ef6551-e0c1-40fc-bf4f-bd0ecf1f8ae7">

Everything was working just fine. I was using the integration on a private repo, and I was paying for it. Then I upgraded to Github Enterprise today. I started seeing the above error message on all the new PRs. 

I tried uninstalling and re-installing the plugin on the Github Marketplace. However, Github knew that I still had an active billing with the integration despite me uninstalling it. I'm not sure what else I should be doing at this point to fix it.

**Comment by noqcks** [comment]
First, sorry for replying so late, I totally missed the notification for this in my inbox. 

Second, I believe this is an issue with GitHub billing... GitHub enterprise plans that are invoiced can't purchase paid plans on the GitHub marketplace, which is really annoying. 

![image](https://github.com/noqcks/pull-request-size/assets/4740147/f5a0591c-b959-4a46-b885-04ca768e9af3)

I invoice via Stripe for these use cases. You can see the instructions here for that: https://github.com/noqcks/pull-request-size/issues/72#issuecomment-1316359463 You can just cancel your subscription via marketplace (if it still exists somehow), and then i'll activate your pro subscription manually. 

I really hope GitHub supports this at some point.
