### ISSUE TITLE
Visibility of Pull Request Size

### ISSUE THREAD

**Issue by Clayton-ResDiary** [noqcks/pull-request-size#158]
Before I am able to purchase for the Org, I need to confirm if all personal GitHub accounts within the org will also be able to see the pull request size without needing to pay an additional $5. Or, would this only be visible to the account with org admin access? Can you clarify?

**Comment by noqcks** [comment]
Yep, $5 will allow all accounts in the organization to see pull request sizes on any PR on repos in the organization.
