### ISSUE TITLE
Question: How to install for an organization?

### ISSUE THREAD

**Issue by alexearnshaw** [noqcks/pull-request-size#21]
Hi, I'm trying to install this app on this repo https://github.com/Axway/axway-open-docs which is owned by an organization. I am an admin of the repo but I am not an admin of the organization.

When I try to install this app, I only get an option to install it on my personal account, and not on the organization account.

![image](https://user-images.githubusercontent.com/29064556/78763544-2e20dd00-797d-11ea-8e20-5fe755b893ff.png)

But for other apps (such as Mergeable) I am able to install on the organization account.

![image](https://user-images.githubusercontent.com/29064556/78763887-aa1b2500-797d-11ea-9aac-91d77d763719.png)

Are additional permissions needed for this app or am I doing something wrong?

**Comment by noqcks** [comment]
Yeah, you'll need to have Admin permissions in the organization in order to install the app for the organization
