### ISSUE TITLE
Not working for my PRs

### ISSUE THREAD

**Issue by TheTechRobo** [noqcks/pull-request-size#24]
In my repo [python-text-calculator](http://github.com/thetechrobo/python-text-calculator) seems like the PR Size bot is no longer doing its job...

My PR [integrate mathmod](https://github.com/TheTechRobo/python-text-calculator/pull/15/) is stuck on size/M label even though it changes more than 100 lines.

My PR [Better base conversion](https://github.com/TheTechRobo/python-text-calculator/pull/18) has no PR Size label at all.

Suspending and unsuspending the app has no apparent effect.

A test PR with 148 commits does not get a label.

**Comment by TheTechRobo** [comment]
This no longer concerns me (I've switched to a github actions), but I'll leave the issue open for anyone else. Sadly it seems like this repo is no longer maintained.

**Comment by noqcks** [comment]
Interesting. Looks like it applied the size/M labels on Aug 12 and then updated it to size/XL on Aug 16.

**Comment by TheTechRobo** [comment]
I don't think this is the case; that one was done by my new GitHub actions. I removed the app from my Marketplace a while ago, as I switched to the github action.

**Comment by TheTechRobo** [comment]
Yes, I think I am correct: the last Pull Request Size one looked like this:

```
pull-request-size (bot) added size/M and removed size/S labels on Aug 12
```

The GITHUB Actions one looked like this:

```
github-actions (bot) added size/xl and removed size/M labels on Aug 16
```

**Comment by noqcks** [comment]
I found and fixed a bug where PRs with deleted files were failing to apply labels (a silly basic oversight). I believe this explains the behaviour of both the PRs you listed. Closing. Please reopen the issue if you use the app again and notice the same behaviour.

**Comment by TheTechRobo** [comment]
I'll try the app sometime.

**Comment by TheTechRobo** [comment]
Wish there was a "remind me" feature in GitHub.
