### ISSUE TITLE
exclude certain file types/extensions from line counts

### ISSUE THREAD

**Issue by nickbouton** [noqcks/pull-request-size#3]
I have a feature request for you: the ability to exclude certain file types/extensions from your line count calculations (if this is possible based on GH app permissions.) I would like to exclude things like Jest snapshots, lock file changes, etc., as they tend to artificially inflate otherwise simple PRs.

And thanks again for this GH extension!

**Comment by noqcks** [comment]
Definitely on my radar! 

I'll try get this in within the next week. 

👌

**Comment by nickbouton** [comment]
@noqcks Hey Benji - appreciate you jumping on this so quickly. I believe you worked with my colleague at Klue, @apawson. (At least, that's what he tells me, should I choose to believe him. He's pretty devious. 😉)

I had a couple of thoughts on this:
- I think your suggestion of a standard set of excluded files and not requiring read-access to repos would make sense in terms of ease-of-distribution. It's probably also the simplest approach in the short-term.
- Having zero (`0`) knowledge about how GitHub "Apps" work, I see a configuration screen in there when I look at your app:

  ![image](https://user-images.githubusercontent.com/169988/49200026-c3ef3580-f34f-11e8-9372-4ed4a049e229.png)

  ![image](https://user-images.githubusercontent.com/169988/49200042-dd907d00-f34f-11e8-8e18-e477f7fa35d2.png)

  My thought there is ... is there any way to make use of that area for configuration, without necessitating full read access to the installed repo?

**Comment by noqcks** [comment]
Apparently you can ask for read-only permissions for a single file! 

![image](https://user-images.githubusercontent.com/4740147/49247532-7fae7480-f3e5-11e8-9f65-ff55f9978fe3.png)

I've added the ability to use custom generated files if specified in `.gitattributes` in [this commit](https://github.com/noqcks/pull-request-size/pull/4/commits/f8cb98d87d9cf7f300482a5ba042967e18b3644a) on #4. 

I'm much more comfortable adding requesting only this permission for repositories.

**Comment by nickbouton** [comment]
@noqcks Nice! Agree on the perms front, the more limited the better.
