### ISSUE TITLE
Stopped running on public repo magma/magma

### ISSUE THREAD

**Issue by ekowtaylor** [noqcks/pull-request-size#39]
This was working fine but stopped all of a sudden on this repo https://github.com/magma/magma/pulls. Can't find any specific errors and not sure how to troubleshoot.  Any pointers will be very helpful.

**Comment by noqcks** [comment]
Yeah... my heroku account was suspended because I forgot to update an expired credit card. whoops!

I took the time to migrate from Heroko to AWS Lambda at the same time. It should be working again.
