### ISSUE TITLE
419 files changed but the pr got labeled XS.

### ISSUE THREAD

**Issue by RDKRACZ** [noqcks/pull-request-size#48]
Link to the pr - https://github.com/RDKRACZ/ConsistencyPlus/pull/39

**Comment by noqcks** [comment]
Sorry I can't see this PR since the repo is private

**Comment by noqcks** [comment]
The link doesn't work. Did you mean this PR? https://github.com/RDKRACZ/ConsistencyPlus/pull/1/files

In this case, since the PR is all pngs the number of lines changed is 0, making the size XS.
