### ISSUE TITLE
`yarn.lock` erroneously included in size 

### ISSUE THREAD

**Issue by noqcks** [noqcks/pull-request-size#5]
`yarn.lock` not being removed from total size calculation, and it should be!

**Comment by Chathula** [comment]
this must be created with a way to ignore files that we want!

**Comment by TheTechRobo** [comment]
yeah, something like a /.github/pull-request-size/ignores with a .gitignore syntax would make sense

**Comment by noqcks** [comment]
It is possible to exclude files in the calculation. I updated the documentation to make it more clear: https://github.com/noqcks/pull-request-size#excluding-files

**Comment by noqcks** [comment]
`yarn.lock` is actually _not_ considered a generated file by the linguist project

see [discussion](https://github.com/github/linguist/issues/4348)

closing this issue
