### ISSUE TITLE
XS->XXL changes and back

### ISSUE THREAD

**Issue by SupinePandora43** [noqcks/pull-request-size#65]
https://github.com/SupinePandora43/UltralightNet/pull/45
(And few other PRs)

+14,990 −31,570
Is problem here?

**Comment by noqcks** [comment]
yeah, mostly likely is a problem, even GitHub says the number of files is infinite. 

<img width="203" alt="image" src="https://user-images.githubusercontent.com/4740147/191778491-ec9d884d-e8ec-4ae2-ad7a-09be2070b206.png">

**Comment by noqcks** [comment]
Just pushed a change to set [max number of files in a PR to 1000](https://github.com/noqcks/pull-request-size/commit/f62face037ffe875f7595e39cbce527fe40e5981#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R7). If this ends up being too low, we can raise. Trying to keep lambda timeout limits relatively low to not endure too many costs.
