### ISSUE TITLE
Comments based on size

### ISSUE THREAD

**Issue by alper** [noqcks/pull-request-size#86]
It would be nice to be able to add comments to the PR as well based on the size of the PR. Especially when it comes to large PRs, we would like to discourage people from making these and give them some strategies how to break up their work.

**Comment by noqcks** [comment]
This is a great suggestion, I will try find some time to work on it next week.

**Comment by noqcks** [comment]
Just added this feature @alper Instructions on how to use it are now in the README 

https://github.com/noqcks/pull-request-size#size-comments
