### ISSUE TITLE
Inquiring About Options for One Acre Fund a Non-Profit Organization

### ISSUE THREAD

**Issue by suwiringSIxbert** [noqcks/pull-request-size#87]
Hi @noqcks,
The [Pull-request-size](https://github.com/noqcks/pull-request-size) has been a nifty tool in our development processes at [One Acre Fund](https://github.com/one-acre-fund).
We are a non-profit organization working with small-holder farmers across Africa and our tech stack relies on open-source technologies and free tools.
I am just contacting you to explore any options available for organizations like ours.

**Comment by noqcks** [comment]
Hi there, I've given One Acre Fund access to the pro plan to free as you're a non-profit. Thanks for reaching out!

https://github.com/noqcks/pull-request-size/commit/6bb4e268506f05ff6e2c30c442da7fa73af9bb22
